name: Automerge

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: ${{ github.event.workflow_run.pull_requests[0].number }}
            })
