name: Automerge

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.actor == 'dependabot[bot]'

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.workflow_run.pull_requests[0].number }},
              event: 'APPROVE'
            });

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.workflow_run.pull_requests[0].number }}
            });
