name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: 14.18.1
  TF_VERSION: 1.0.10

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: 'password'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - run: echo '${{ toJSON(github) }}'

      - uses: actions/checkout@v2

      - uses: nanasess/setup-chromedriver@v1

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}

      - run: ./bin/setup

      - run: RAILS_ENV=test ./bin/rails webpacker:compile

      - run: ./bin/test

      - run: ./bin/quality

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi

  terraform:
    strategy:
      matrix:
        tf_dir:
          - terraform/app_environment
          - terraform/app_global

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - run: terraform fmt -check -recursive

      - run: terraform init -backend=false

      - run: terraform validate

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi

  deploy:
    if: github.ref == 'refs/heads/main'

    needs: [test, terraform]

    strategy:
      max-parallel: 1

      matrix:
        tf_workspace: [staging, production, global]
        include:
          - tf_workspace: staging
            tf_dir: terraform/app_environment
          - tf_workspace: production
            tf_dir: terraform/app_environment
          - tf_workspace: global
            tf_dir: terraform/app_global

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}

    env:
      TF_WORKSPACE: ${{ matrix.tf_workspace }}

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - run: terraform init

      - run: terraform apply -lock-timeout=30s

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi
